[tool.poetry]
name = "aoc-2022"
version = "0.1.0"
description = ""
authors = ["s-braitsch <simon.braitsch@novatec-gbmh.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
